messages:
  start:
    cmdStartPrivate: "ะะปั ะพะฑัะตะฝะธั ัะพ ัะปััะฐะนะฝัะผ ัะพะฑะตัะดะตะฝะธะบะพะผ ะฒะพัะฟะพะปัะทัะนัะตัั ะบะปะฐะฒะธะฐัััะพะน ั ะบะฝะพะฟะบะฐะผะธ."
  help: "ะะพั-ะผะพะดะตัะฐัะพั ะฒ ะณััะฟะฟะฐั. ะะฝะพะฝะธะผะฝัะน ัะฐั ะฒ ะะธัะฝัั ะกะพะพะฑัะตะฝะธัั ั ะฑะพัะพะผ."
  callAll:
    correctUsage: "{name}, ะฟัะฐะฒะธะปัะฝะพะต ะธัะฟะพะปัะทะพะฒะฐะฝะธะต ะบะพะผะฐะฝะดั: /callall <ัะพะพะฑัะตะฝะธะต>"
  moderator:
    kickSelf: "{name}, ะฒั ะฝะต ะผะพะถะตัะต ะบะธะบะฝััั ัะฐะผะพะณะพ ัะตะฑั!"
    usernameCorrect: "{name}, ะตัะปะธ ะฒั ัะพัะธัะต ะบะธะบะฝััั ัะตะปะพะฒะตะบะฐ, ะธัะฟะพะปัะทัั @username, ัะพ: /kick <@username>"
    userKicked: "{mention.kicked} ะฑัะป ะบะธะบะฝัั {mention}"
    userNotFound: "ะะพะปัะทะพะฒะฐัะตะปั ะฝะต ะฝะฐะนะดะตะฝ"
  noChatPermission: "ะฃ ะฑะพัะฐ ะฝะตั ะฝะตะพะฑัะพะดะธะผัั ัะฐะทัะตัะตะฝะธะน ะดะปั ะฟะพะปะฝะพัะตะฝะฝะพะน ัะฐะฑะพัั ะฑะตะท ัะฑะพะตะฒ!"
  noPermission: "ะฃ ัะตะฑั ะฝะตั ะฟัะฐะฒ!"
  chat:
    alreadyInChat: "ะั ัะถะต ะฝะฐัะพะดะธัะตัั ะฒ ัะฐะทะณะพะฒะพัะต, ะทะฐะฒะตััะธัั ะตะณะพ - /stop"
    userFound: "ะกะพะฑะตัะตะดะฝะธะบ ะฝะฐะนะดะตะฝ!\n\nะัะตะบัะฐัะธัั ะพะฑัะตะฝะธะต - /stop"
    userInQueue: "ะั ะฒ ะพัะตัะตะดะธ, ะฟะพะบะฐ ััะพ ะฒ ะฑะพัะต ะผะฐะปะพ ะปัะดะตะน, ะฟะพััะพะผั ะฟะพะธัะบ ะผะพะถะตั ะทะฐะฝััั ะฝะตัะบะพะปัะบะพ ะผะธะฝัั. ะั ะผะพะถะตัะต ะฒัะนัะธ ะธะท ะดะธะฐะปะพะณะฐ ั ะฑะพัะพะผ, ะฒะฐะผ ะฟัะธะดะตั ัะฒะตะดะพะผะปะตะฝะธะต."
    dialogStopped: "ะะธะฐะปะพะณ ะพะบะพะฝัะตะฝ โ๏ธ\n\nะะปั ะฟะพะธัะบะฐ ะฝะพะฒะพะณะพ ัะพะฑะตัะตะดะฝะธะบะฐ ะฒะพัะฟะพะปัะทัะนัะตัั ะบะปะฐะฒะธะฐัััะพะน ั ะบะฝะพะฟะบะฐะผะธ."

databaseDefPath: "databases/db/def_db.db"
callAllEmojies: ['๐คก', '๐ฅถ', '๐ฅต', '๐พ', '๐คช', '๐ฐ', '๐ต', '๐คฏ', '๐ฉ', '๐จ', '๐ฑ', '๐ต', '๐ฅด', '๐ก', '๐', '๐ท', '๐คฌ', '๐คง', '๐', '๐คฎ', '๐คข', '๐ค', '๐ค', '๐ฅณ', '๐ฅธ', '๐ฅบ', '๐ฅน', '๐ค', '๐ซฃ', '๐ซข', '๐คญ', '๐คซ', '๐คฅ', '๐ง', '๐', '๐บ', '๐น', '๐ฟ', '๐', '๐ค', 'โ', ๏ธ '๐ป', '๐ฝ', '๐ค', '๐ฉ']